tasks 2,3
capetown-team/capetown-game pull request #23
Opened 2021-02-08 15:07 UTC by anastasia1188

2021-02-08 15:52 UTC, AndZhr commented on src/components/Button/Button.scss
> +}
Для git в конце файлов должна быть пустая строка

2021-02-08 15:52 UTC, AndZhr commented on src/components/App/App.tsx
> +    isPrivate: true
isPrivate здесь означает, что страница доступна только авторизованным пользователям. Для страниц login и registration должно быть false в этом поле.

2021-02-08 15:52 UTC, AndZhr commented on src/pages/Autorisation/index.tsx
> +export { Autorisation }from './Autorisation';
Нет пробелы перед from

2021-02-08 15:52 UTC, AndZhr commented on src/components/Button/Button.tsx
> +export function Button(props: ButtonProps) {
У нас везде стрелочные функции используются и в других файлах у тебя стрелочная функции, нужно переписать на:
`export const Button = (props: ButtonProps) => {`

2021-02-08 15:52 UTC, AndZhr commented on src/components/Input/Input.tsx
> +export function Input(props: InputProps) {
Нужно поменять с function на стрелочную функцию.

2021-02-08 15:52 UTC, AndZhr commented on src/pages/Autorisation/Autorisation.tsx
> +import { Input } from '../../components/Input';
У нас настроен alias "@" который указывает на папку src, лучше использовать его вместо относительных путей:
`import { Button } from ' @/components/Button';`

2021-02-08 15:52 UTC, AndZhr commented on src/components/Button/Button.scss
> +.button {
Лучше оставлять пустую строку после импортов, так как это логически разные части кода.

2021-02-08 15:52 UTC, AndZhr commented on src/components/Button/Button.tsx
> +interface ButtonProps
Здесь тоже лучше оставить пустую строку после импорта, так как логически интерфейс к нему не относится.

2021-02-08 19:54 UTC, iibadreeva reviewed
В целом хорошо, но можно немного поправить, поскольку компонеты могут быть часто переиспользоваными на любой странице

2021-02-08 19:54 UTC, iibadreeva commented on src/components/Button/Button.tsx
> +        <React.Fragment>
<React.Fragment> используется если мы не хотим что бы наш компонет был обернуть в какой либо тег, а ты использует после button, можно использовать этот тег как обертку
Пример когда можно использовать Fragment 
```
<Fragment>
  <div>test</div>
  <div>test</div>
  <div>test</div>
</Fragment>
```

2021-02-08 19:54 UTC, iibadreeva commented on src/components/Button/Button.tsx
> +        <button className = "button">
В тег button необходима возможность указывать класс, так же доп. параметры {...props} поскольку этот компонент может быть часто переиспользованным и в будущем могут понадобится другие теги и обработчики события (например handlerClick)

2021-02-08 19:54 UTC, iibadreeva commented on src/components/Input/Input.scss
> +}
в конце нужно добавить новую строчку, можно кстати включить stylelint плагин для твоего редактора, он будет подсказывать что есть ошибка

2021-02-08 19:54 UTC, iibadreeva commented on src/pages/Autorisation/index.tsx
> +export { Autorisation }from './Autorisation';
Можно включить prettier для твоего плагина, он будет автоматом добавлять новую строчку

2021-02-08 19:54 UTC, iibadreeva commented on src/pages/Autorisation/Autorisation.tsx
> +export const Autorisation = (): JSX.Element => (
Можно заменить на такой синтаксис
`const Autorisation: FC = () => {`

2021-02-08 19:54 UTC, iibadreeva commented on src/pages/Registration/Registration.scss
> +@import '../../styles/common/login';
Можно ставить пустую строку между импортами и стилям

2021-02-08 20:04 UTC, DmitryKhitrin commented on src/components/App/App.tsx
> +    component: Autorisation,
`Authorization`

2021-02-08 20:05 UTC, DmitryKhitrin commented on src/components/Button/Button.scss
> +    margin: auto;
Не стоит задавать марджины кнопке, это сделает родительский компонент

2021-02-08 20:06 UTC, DmitryKhitrin commented on src/components/Button/Button.tsx
> +export function Button(props: ButtonProps) {
А на самом деле `export const Button: FC<Props> = () => {}`

2021-02-08 20:08 UTC, DmitryKhitrin commented on src/components/Button/Button.tsx
> +        <button className = "button">
Так же если жто общи компонент кнопки, то хотелось бы еще иметь возможность передать в нее:
`onClick`, `placeholder`

2021-02-08 20:10 UTC, DmitryKhitrin commented on src/components/Input/Input.scss
> +    width: 280px;
Это общий компонент не стоит так строго задавать стили, можно сделать модификатор size:
`type Size = 's' | 'm' | 'l'` и в эти модификаторах задавать уже размер, так получится более гибкое решение.

2021-02-08 20:12 UTC, DmitryKhitrin commented on src/components/Input/Input.tsx
> +    children?: string | never[];
- Зачем объявлен children, если он не используется?
- Зачем тут id?
- Наверное мы захотим, что бы инпут принимал сверху функция на onChange)

2021-02-08 20:12 UTC, DmitryKhitrin commented on src/components/Input/Input.tsx
> +        <React.Fragment>
Фрагмент тут не нужен)

2021-02-08 20:13 UTC, DmitryKhitrin commented on src/pages/Autorisation/Autorisation.tsx
> +export const Autorisation = (): JSX.Element => (
Если нет пропсов, то FC не нужен.

2021-02-08 20:16 UTC, DmitryKhitrin commented on src/pages/Autorisation/Autorisation.tsx
> +                    </Input>
Тут можно без закрывающего тега  `<Input id="password" placeHolder="Пароль /">`

2021-02-08 20:18 UTC, DmitryKhitrin requested changes
Очень не плохо, видно что ты начинаешь разбираться как работает React, но некоторые штуки все же придется поправить( Если будут вопросы приходи!)

2021-02-09 23:30 UTC, DmitryKhitrin commented on src/components/Button/Button.tsx
> +  // Поребейсь ветку на мастер, там появилась библиотека что бы разруливать такие места
Ну не надо было прям мой коммит вливать, я просто пофкисил линт и пару проблем) И все же поребейз ветку, есть некоторое количество конфликтов с мастером)

2021-02-09 23:31 UTC, DmitryKhitrin commented on src/pages/Autorization/Autorization.tsx
> +            <span>Вход</span>
Это тоже тестовый кусок, что бы показать, что кнопка теперь принимает как строку так и children

2021-02-09 23:32 UTC, DmitryKhitrin commented on .eslintrc.json
>          "extensions": [".js", ".ts", ".tsx", ".scss"]
А что с `package-lock` произошло?

2021-02-10 10:24 UTC, closed without merging

2021-02-10 13:18 UTC, iibadreeva reviewed
Есть ошибки которые необходимо поправить

2021-02-10 13:18 UTC, iibadreeva commented on src/pages/Autorization/Autorization.tsx
> +  <div className="body">
Мне кажется это тут должен быть тег main с классом form, поскольку мы делаем все по методологии bem, значит и все остальные классы в нутрий ребенка должны называться .form__wrap, form__input, form_title, form__lable, так же желательно попробовать библиотеку 'bem-cn-lite', на странице leaders я уже использую ее

2021-02-10 13:18 UTC, iibadreeva commented on src/components/App/App.tsx
> +<Autorization/>
Тут лишнее

2021-02-10 13:18 UTC, iibadreeva commented on src/pages/Autorization/Autorization.tsx
> +          <Input placeholder="Пароль" />
У тебя передается атрибут placeholder, но нет type,  а ведь пароли мы делаем
`<input placeholder="Пароль" type="password">`
Еще в данный компонет могут добавляться и другие атрибуты или нет , нужно это учитывать, пример
`<input placeholder="Пароль" type="password" data-type="password"  value="" autocomplete="off" autocapitalize="off" autocorrect="off">`

2021-02-10 13:18 UTC, iibadreeva commented on src/pages/Autorization/Autorization.tsx
> +          <Button type="submit" size="s">
Данный компонет ожидает onClick ` <Button type="submit" size="s" onClick={() => {}}>`

2021-02-10 13:18 UTC, iibadreeva commented on src/pages/Autorization/Autorization.tsx
> +            <a href="/registration">Регистрация</a>
Тег **a** обычно не используются в react, используется Link из библиотеки например в нашем  случаи react-router-dom
```
import { Link } from 'react-router-dom';
<Link className={b('link')} to="/registration">Регистрация</Link>
```

2021-02-10 13:18 UTC, iibadreeva commented on src/pages/Registration/Registration.scss
> +}
Необходимо пробежаться по всем файлам scss и убедиться что там добавлена новая строка в конце каждого файла **stylelint** должен помогать тебе увидеть ошибки