Авторизация
capetown-team/capetown-game pull request #28
Opened 2021-02-10 14:55 UTC by anastasia1188

2021-02-10 16:20 UTC, iibadreeva requested changes

2021-02-10 16:20 UTC, iibadreeva commented on src/components/App/App.tsx
> +    isPrivate: false
path: '*' = это все остальное, необходимо что бы это оставалось последним в пункте, а то никто не сможет попасть на страницы login и registration, так как * подходит под все остальное, следовательно мы будет попадать на страницу с ошибкой

2021-02-10 16:20 UTC, iibadreeva commented on src/pages/Autorization/Autorization.tsx
> +  <div className="body">
Мне кажется это тут должен быть тег main с классом form, поскольку мы делаем все по методологии bem, значит и все остальные классы в нутрий родителя должны называться .form__wrap, form__input, form_title, form__lable, так же желательно попробовать библиотеку 'bem-cn-lite', на странице leaders я уже использую ее

2021-02-10 16:20 UTC, iibadreeva commented on src/pages/Autorization/Autorization.tsx
> +          <Input placeholder="Пароль" />
У тебя передается атрибут placeholder, но нет type, а ведь пароли мы делаем
<input placeholder="Пароль" type="password">
Еще в данный компонент могут добавляться и другие атрибуты или нет , нужно это учитывать, пример
<input placeholder="Пароль" type="password" data-type="password" value="" autocomplete="off" autocapitalize="off" autocorrect="off">

2021-02-10 16:20 UTC, iibadreeva commented on src/pages/Autorization/Autorization.tsx
> +          <Button type="submit" size="s">
Желательно добавить возможность добавлять остальные атрибуты, это может пригодится в будущем

2021-02-10 16:20 UTC, iibadreeva commented on src/pages/Autorization/Autorization.tsx
> +            <a href="/registration">Регистрация</a>
Тег **a** обычно не используются в react, используется Link из библиотеки например в нашем  случаи react-router-dom
```
import { Link } from 'react-router-dom';
<Link className={b('link')} to="/registration">Регистрация</Link>
```

2021-02-10 16:20 UTC, iibadreeva commented on src/pages/Registration/Registration.scss
> +}
Необходимо пробежаться по всем файлам scss и убедиться что там добавлена новая строка в конце каждого файла stylelint должен помогать тебе увидеть ошибки

2021-02-10 16:20 UTC, iibadreeva commented on src/styles/common/login.scss
> +@import '@styles/layout/colors';
Как у тебя запустился проект, с данной ошибкой?
Должно быть хотя бы так  
`@import '../../styles/layout/colors';`

2021-02-10 16:20 UTC, iibadreeva commented on src/styles/common/login.scss
> +    top: calc(50% - 512px/2 + 7px);
Ошибка по правилам **stylelint**, необходимо разделять пробелами 
`top: calc(50% - 512px / 2 + 7px);`

2021-02-11 09:42 UTC, DmitryKhitrin commented on src/components/Button/Button.tsx
> +const Button: FC<Props> = ({ size, children, onClick }) => {
`const Button: FC<Props> = ({ size, = 's' children, onClick }) => {`

2021-02-11 09:42 UTC, DmitryKhitrin commented on src/components/Button/Button.tsx
> +  const className = b({ size: 's' });
А здесь просто size в твоем варианте кнопка всегда будет размера s(

2021-02-11 09:42 UTC, DmitryKhitrin commented on src/components/Input/Input.scss
> +  width: 280px;
Лучше не пользоваться фикс значениями

2021-02-11 09:43 UTC, DmitryKhitrin commented on src/components/Input/Input.scss
> +  width: 280px;
Инпут вроде должен растягиваться под родителя

2021-02-11 09:43 UTC, DmitryKhitrin commented on src/components/Input/Input.tsx
> +type inputProps = {
Тип с больщой буквы

2021-02-11 09:44 UTC, DmitryKhitrin commented on src/pages/Registration/Registration.tsx
> +  <div className="body">
Тут кажется тоже нужен `bem-cn`

2021-02-11 09:44 UTC, DmitryKhitrin approved these changes
В целом ок, но комментарии стоит поправить

2021-02-11 17:27 UTC, AndZhr commented on src/components/App/App.tsx
> +    isPrivate: false
Нужно подтянуть изменения на ветке sprint-5 и поправить конфликт, роуты теперь в отдельном файле

2021-02-12 18:24 UTC, iibadreeva approved these changes

2021-02-12 18:24 UTC, iibadreeva commented on src/pages/Autorization/Autorization.scss
> +  }
Не много странно что два одинаковых класса, в разных файлах https://prnt.sc/z8u2de

2021-02-12 18:24 UTC, iibadreeva commented on src/pages/Autorization/Autorization.tsx
> +            <Input placeholder="Пароль" />
Нужна возможность передавать класс, или только на странице регистрации или авторизации будет компонент использоваться?

2021-02-12 18:24 UTC, iibadreeva commented on src/pages/Registration/Registration.tsx
> +
Все библиотеку лучше подключать с верху, стили в конце, и разделить новой строкой, например: 

```
import React from 'react';
import block from 'bem-cn-lite';
import { Link } from 'react-router-dom';

import { Button } from '@/components/Button';
import { Input } from '@/components/Input';

import './Autorization.scss';
```

2021-02-13 08:06 UTC, closed without merging

2021-02-13 08:06 UTC, anastasia1188 commented
изменения смерджены с главной веткой