Валидация + апи
capetown-team/capetown-game pull request #30
Opened 2021-02-11 18:59 UTC by anastasia1188

2021-02-12 10:16 UTC, iibadreeva reviewed
Я как понимаю ты взял работу Анастасии, даже не знаю кого просить причесать, или можно после всех страниц, кому-то пройтись и причесть

2021-02-12 10:16 UTC, iibadreeva commented on src/api/login.ts
> +interface User {
Почему interface а не type?

2021-02-12 10:16 UTC, iibadreeva commented on src/api/login.ts
> +export async function isAutorizied(user: User) {
Мы вроде используем везде стрелочную функцию

2021-02-12 10:16 UTC, iibadreeva commented on src/api/login.ts
> +    const response = await fetch(`${host}/auth/signin`, {
Я еще на встрече спросила что мы будем использовать fetch or axious, договорились на axious

2021-02-12 10:16 UTC, iibadreeva commented on src/modules/validation.ts
> +export function isValidEmail(email: string) {
Так же не стрелочные функции

2021-02-12 10:16 UTC, iibadreeva commented on src/pages/Autorization/Autorization.tsx
> +              <a href="/registraion">Регистрация</a>
Нужно использовать `import {Link} from "react-router-dom";`

2021-02-12 10:16 UTC, iibadreeva commented on src/pages/Autorization/Autorization.tsx
> +    <div className="body">
Мы используем bem, такой класс как body не допустим

2021-02-12 13:28 UTC, DmitryKhitrin commented on src/api/login.ts
> +  return axios
Лучше делать не так, лучше сделать базовый api класс:


import axios from "axios";
import {history} from "../utils/history";

export const makeApi = () => {
  const api = axios.create({
    baseURL: ``api_url`,`
    timeout: 5000,
    withCredentials: true
  });
  api.interceptors.response.use(
      (response) => {
        return response;
      },
      (error) => {
        const {status} = error.response;
        return Promise.reject(error);
      }
  );
  return api;
};

2021-02-12 13:31 UTC, DmitryKhitrin commented on src/api/login.ts
> +  return axios
И потом отдельно описать ручки

2021-02-12 13:33 UTC, DmitryKhitrin commented on src/api/login.ts
> +    phone: '+79191234567',
Лучше сделать это поле опциональным, по умолчанию null

2021-02-12 13:33 UTC, DmitryKhitrin commented on src/api/login.ts
> +    .catch(function (error) {
`() => {}` стрелочные функции вроде же используем

2021-02-12 13:34 UTC, DmitryKhitrin commented on src/components/Button/Button.scss
> +}
Стоит добавить пустую строчку

2021-02-12 13:34 UTC, DmitryKhitrin commented on src/components/Button/Button.tsx
> +const Button: FC<Props> = ({ size, children, onClick, disabled }) => {
Кнопка же в другой таске уже была сделана?

2021-02-12 13:34 UTC, DmitryKhitrin commented on src/components/Button/Button.tsx
> +      className={className}
className={b({ size });}

2021-02-12 13:35 UTC, DmitryKhitrin commented on src/components/Input/Input.tsx
> +export const Input: FC<InputProps> = ({
Инпут вроже же тоже в другой таске делался?

2021-02-12 13:36 UTC, DmitryKhitrin commented on src/modules/validation.ts
> +  let result = '';
Зачем тут объявлять переменную, можно просто сделать return в условиях), получим ранний выход из функии, что кажется оптимальней

2021-02-12 13:36 UTC, DmitryKhitrin commented on src/modules/validation.ts
> +  if (password.length < 8) {
Ранней выход

2021-02-12 13:37 UTC, DmitryKhitrin commented on src/pages/Autorization/Autorization.scss
> +.form__title {
Стили описываются кажется не так:

```
.form {
    __title:
    
    __ main:

}
```

2021-02-12 13:38 UTC, DmitryKhitrin commented on src/pages/Autorization/Autorization.tsx
> +export const Autorization = () => {
Authorization

2021-02-12 13:38 UTC, DmitryKhitrin commented on src/pages/Autorization/Autorization.tsx
> +  const [login, setLogin] = useState('');
Это всю логику можно вынести в хук useAuthorization, что бы не загромождать компонент)

2021-02-12 13:40 UTC, DmitryKhitrin commented on src/pages/Registration/Registration.tsx
> +    const elementLogin = document.getElementById('login') as HTMLInputElement;
В react мы не работаем с html, у нас есть возможность работать с данными напрямую!
https://kanby.medium.com/валидация-форм-в-reactjs-56341da641d0
https://ru.reactjs.org/docs/forms.html

2021-02-12 13:40 UTC, DmitryKhitrin commented on src/pages/Registration/Registration.tsx
> +  const passwordConfirmHandler = (e: ChangeEvent<Element>) => {
Весь функционал будет удобнее вынести в хук)

2021-02-12 13:42 UTC, DmitryKhitrin commented on src/pages/Registration/Registration.tsx
> +    const text = (e.target as HTMLInputElement).value;
Смотри, так делать не правильно, как стоит делать:

```
[value, setValue] = useState('');
const handleChange = useCallback((e) => {
// какая-то логика
setValue(e.target.value);
})
<input onChange={handleChange}>{value}</input>
```

Нам нет нужды лезть напрямую в DOM

2021-02-12 13:43 UTC, DmitryKhitrin commented on src/styles/common/login.scss
> +.form__login {
Посмотри как оформлен css в остальном проекте)

2021-02-12 13:44 UTC, DmitryKhitrin requested changes
Привет, все выглядит оч не плохо, кроме одного очень важного момента. Мы работаем react и нам нет нужды лезть напрямую в DOM за данными для работы с [формой](https://ru.reactjs.org/docs/forms.html):

Ну и стоит поправить работу с css)

2021-02-12 13:46 UTC, AndZhr commented on src/modules/regExps.ts
> +  '^([a-z0-9_-]+.)*[a-z0-9_-]+@[a-z0-9_-]+(.[a-z0-9_-]+)*.[a-z]{2,6}$'
Символ `.` обозначает любой символ, что бы проверять именно точку нужно его экранировать `\.`
Сейчас под эту регулярку подойдёт например `mail@example^com`
Можно использовать такое `/^\S+@\S+\.\S+$/`

2021-02-12 13:46 UTC, AndZhr commented on src/modules/regExps.ts
> +export const REXP_LOGIN = new RegExp('^([a-z0-9_-]+.)*[a-z0-9_-]$');
Здесь тоже из-за точки подойдёт например `h@f#llo`
А вот заглавные буквы как раз не подойдут, `Den11` не проходит
Можно использовать например вот такое `/^[a-z_\-.0-9]{4,}$/i`

2021-02-12 13:46 UTC, AndZhr commented on src/modules/regExps.ts
> +export const REXP_NUMERAL = /[0-9]/;
Для чисел есть символьный класс `\d`

2021-02-12 13:46 UTC, AndZhr commented on src/pages/Autorization/Autorization.tsx
> +import { Input } from '@/components/Input';
А откуда Button и Input, если они в прошлом pull request созданы, но он ещё не влит в ветку sprint-5?

2021-02-13 12:20 UTC, DmitryKhitrin commented on src/api/login.ts
> +  return axios
Повторюсь еще раз, ручки стоит описывать отдельно

```
import { api } from "./api";

const authApi = () => {
  const signUp = (user: SignUpUser) => {
    return client.post<User>(`${path}/signup`, user, { withCredentials: true });
  };

  const signIn = (user: SignInUser) => {
    return client.post<User>(`${path}/signIn`, user, { withCredentials: true });
  };

  const logout = () => {
    return client.post(`${path}/logout`, {}, { withCredentials: true });
  };

  return {
    signUp,
    signIn,
    logout,
  };
};

```

Как пример

2021-02-13 16:00 UTC, iibadreeva approved these changes
Веки лучше писать sprint-5_task_#
Логику можно вынести в hook, а то много повторяющих вещей

2021-02-13 18:06 UTC, DmitryKhitrin approved these changes

2021-02-13 18:26 UTC, DmitryKhitrin approved these changes

2021-02-14 07:26 UTC, merged