хук Авторизации useAuth
capetown-team/capetown-game pull request #51
Opened 2021-02-19 07:25 UTC by anastasia1188

2021-02-22 09:34 UTC, iibadreeva requested changes
Как поняла ты делаешь валидацию? Тогда валидировать необходимо все формы включая страницу профиля

2021-02-22 09:34 UTC, iibadreeva commented on src/hooks/useAuth.tsx
> +export const useAuth = (type: TypeAuth) => {
У тебя назван хук useAuth, этот хук должен запрашивать авторизован пользователь или нет, может должно быть useValidatioin?

2021-02-25 18:44 UTC, iibadreeva approved these changes

2021-03-05 05:32 UTC, closed without merging

2021-03-05 05:32 UTC, anastasia1188 commented
в бэклог, пока закрою, чтобы не вносило путаницу