webAPI (FullScreen)
capetown-team/capetown-game pull request #52
Opened 2021-02-19 09:30 UTC by anastasia1188

2021-02-19 12:23 UTC, iibadreeva requested changes
Есть ли демо? А то вроде как готово, а реализации нет

2021-02-19 12:24 UTC, iibadreeva requested changes
Есть ли демо? А то вроде как готово, а реализации нет

2021-02-19 12:24 UTC, iibadreeva commented on src/modules/webApi.tsx
> +    });
Что тут делает dom?

2021-02-19 12:26 UTC, iibadreeva commented on src/modules/webApi.tsx
> +    });
Мы вроде делаем все на React

2021-02-19 13:50 UTC, anastasia1188 commented on src/modules/webApi.tsx
> +    });
> Мы вроде делаем все на React
правлю, из задания взяла, реализацию тестировала локально на странице игры, в pr не включала.

2021-02-19 16:48 UTC, iibadreeva commented on src/modules/webApi.tsx
> +    });
Надо что бы при разворачивании оставалась только игра, и кнопки управления, а тут на все, лучше это сделать как hook, что бы можно было разворачивать все что угодно

2021-02-19 17:25 UTC, anastasia1188 commented on src/modules/webApi.tsx
> +    });
для этого там есть второй параметр target - это элемент, который надо разворачивать

2021-02-19 21:24 UTC, DmitryKhitrin commented on src/modules/webApi.tsx
> +    });
Если что элемент можно получить через ref

2021-02-21 13:28 UTC, iibadreeva approved these changes
Все отлично, но мне кажется что можно менять текст с "На весь экран" => "Обычный экран"  и при клике возвращать и разве это не хук?

2021-02-21 13:28 UTC, iibadreeva commented on src/pages/Game/Game.tsx
> +          <Button disabled={!isStart} onClick={handleStop} size="small">
Нужно добавить еще класс, а то кнопки слиты в месте size="small game__button"

2021-02-22 21:22 UTC, AndZhr approved these changes

2021-02-22 21:22 UTC, AndZhr commented on src/modules/webApi.tsx
> +type Func = () => void;
Возможно имеет смысл переименовать файл из "webApi" в "fullScreenApi", например, так как дальше мы будем подключать и другие web Api и лучше их разнести в разные файлы.

2021-02-24 07:52 UTC, merged