init
capetown-team/capetown-game pull request #61
Opened 2021-02-26 15:14 UTC by anastasia1188

2021-02-27 20:40 UTC, iibadreeva requested changes
Пока авторизация не срабатывает (проходит с ошибкой), селекторы не используются

2021-02-27 20:40 UTC, iibadreeva commented on src/pages/Registration/Registration.tsx
>        history.replace(ROUTES.GAME);
Не понятно зачем тут await?
Почему authorize тут и что что он передает?

2021-02-28 07:47 UTC, DmitryKhitrin commented on src/pages/Authorization/Authorization.tsx
> +// import { signInSelector } from '@/reducer/signin/selectors';
А зачем тут закомментированный код? Если эти импорты не нужны, думаю стоит их удалить)

2021-02-28 07:48 UTC, DmitryKhitrin commented on src/pages/Authorization/Authorization.tsx
> +      await dispatch(checkSignIn(user));
Зачем await у диспатча?

2021-02-28 07:48 UTC, DmitryKhitrin commented on src/pages/Authorization/Authorization.tsx
> +      console.log(err);
Зачем тут console.log?

2021-02-28 07:49 UTC, DmitryKhitrin commented on src/pages/Authorization/Authorization.tsx
> +    const userAuth = {
Зачем тут объект с пустыми данными?

2021-02-28 07:49 UTC, DmitryKhitrin commented on src/pages/Registration/Registration.tsx
> +      await dispatch(checkSignUp(user));
Те же вопросы что и в авторищации. И чем авторизация отличается от регистрации в данном кейсе?

2021-02-28 07:52 UTC, DmitryKhitrin commented on src/reducer/signin/reducer.tsx
> +        error: false
свойства pending и error можно объединить в одно:

`status: "error" | "pending" | "success";`

2021-02-28 07:52 UTC, DmitryKhitrin commented on src/reducer/signin/reducer.tsx
> +        isSignIn: true,
isAuthorized можно унести в ветку данных о юзере

2021-02-28 07:54 UTC, DmitryKhitrin commented on src/reducer/signup/actions.tsx
> +export type SignUpState = {
Чем это отличается от signIn state? Почему это разные ветки? Может можно объедегить это все в рамках user.reducer и user.actions?

2021-02-28 07:54 UTC, DmitryKhitrin requested changes
Ветки с sginIn и signup стоит объединить в рамках user

2021-02-28 17:39 UTC, iibadreeva requested changes

2021-02-28 17:39 UTC, iibadreeva commented on src/pages/Registration/Registration.tsx
> +    if (isSignUp) {
Зачем делать дополнительную проверку, можно проверять  isAuth после отправки формы

2021-02-28 17:39 UTC, iibadreeva commented on src/reducer/signup/actions.tsx
>            dispatch(signUp(user));
Зачем тут надо что-то передавать? Ты же все равно эти данные не будешь использовать, данные поученные нужно передать в  authorize(user), тогда они обновятся в шапке и на любой странице где используются
signUp можно добавить как флаг, что прошла авторизация и например можно спрятать лоудер

2021-03-01 19:33 UTC, AndZhr commented on src/index.tsx
>        .register('/sw.js')
Нужно сделать rebase на ветку sprint-6, там исправлен service worker

2021-03-01 19:33 UTC, AndZhr commented on webpack.config.js
> +  port: 8003
Это изменение тоже можно убрать после rebase

2021-03-01 22:13 UTC, iibadreeva approved these changes
В целом уже работает, можно немного поправить и сделать лучше

2021-03-01 22:13 UTC, iibadreeva commented on src/reducer/signup/selectors.tsx
> +export const signUpSelector = (state: AppState) => state.signup.isSignUp;
Раз мы создали эти селекторы, значит мы можем их тоже использовать
pendingSelector - показываем <Loading/>
signUpSelector - скрываем  <Loading/>
Просто у нас всем может быстро происходить, но бывают задержки, и тогда выглядит как зависания

2021-03-01 22:13 UTC, iibadreeva commented on src/reducer/signup/selectors.tsx
> +export const userSelector = (state: AppState) => state.signup.user;
userSelector  этот селектор думаю наврали будет использоваться где либо

2021-03-01 22:13 UTC, iibadreeva commented on src/reducer/signup/actions.tsx
> +          dispatch(signUp(user));
тут можно просто` dispatch(signUp());`

2021-03-01 22:13 UTC, iibadreeva commented on src/reducer/signup/reducer.tsx
> +        },
лишнее

2021-03-01 22:13 UTC, iibadreeva commented on src/reducer/signin/selectors.tsx
> +export const userSelector = (state: AppState) => state.signin.user;
Лишний, наврали где либо будет использоваться

2021-03-02 17:53 UTC, AndZhr approved these changes

2021-03-03 06:23 UTC, DmitryKhitrin commented on src/index.tsx
> -    navigator.serviceWorker
Это точно изменения из твой ветки? Может стоит сделать rebase на мастер?

2021-03-03 06:24 UTC, DmitryKhitrin commented on src/pages/Authorization/Authorization.tsx
> +  useEffect(() => {
Тут кажется не нужен useEffect, можно сразу использовать pending:

```

if (pendign) {
     return <Loading/>
}

```

2021-03-03 06:26 UTC, DmitryKhitrin approved these changes

2021-03-03 06:26 UTC, DmitryKhitrin commented
Почитай пожалуйста прошлые комменты, если их исправила, то на них можно жмакнуть resolve. Так же стоит перед мерджем ребейзнуться.

2021-03-03 10:56 UTC, anastasia1188 commented
> Почитай пожалуйста прошлые комменты, если их исправила, то на них можно жмакнуть resolve. Так же стоит перед мерджем ребейзнуться.

ок, да, прошлые комменты, кроме ребейз,  исправила

2021-03-03 14:07 UTC, merged