Добавить API на страницу профиля (sprint 6 task 15)
capetown-team/capetown-game pull request #75
Opened 2021-03-02 21:50 UTC by AndZhr

2021-03-02 23:59 UTC, iibadreeva requested changes
У меня на странице профиля ошибка в консоли `Uncaught TypeError: Cannot read property 'avatar' of null`
Еще при изменении, данных запросы могут быть медленнее чем при разработке, можно в просматривать в режиме slow|fast3g (network)>, можно например информировать о том что данные отправляются и показывать loader

2021-03-02 23:59 UTC, iibadreeva commented on src/reducer/profile/actions.tsx
> +
Код дублируется, можно взять (import) из auth authorize

2021-03-02 23:59 UTC, iibadreeva commented on src/pages/Profile/Profile.tsx
> +      }
Обычно мы используем ?? если нам нужно проверить ноль

2021-03-02 23:59 UTC, iibadreeva commented on src/pages/Profile/Profile.tsx
> +  });
isProfileView в файле selectors отсутствует, можно добавить а не обращаться на прямую
`import { userSelector } from '@/reducer/profile/selectors';`
После объединить 
```
const { user, isProfileView } = useSelector((state: AppState) => {
    return {
      user: authSelector(state),
      isProfileView: userSelector(state)
    };
  });
```

2021-03-02 23:59 UTC, iibadreeva commented on src/reducer/profile/actions.tsx
> +  };
У меня не все картинки загружаются, можно добавить catch обработку ошибок и информировать об этом

2021-03-03 06:22 UTC, DmitryKhitrin commented on src/reducer/profile/actions.tsx
> +
В данному случае лучше просто соединить эти ветки в один reducer. userReducer в котором будет знание о залогине и данные о юзере.

2021-03-03 15:09 UTC, AndZhr commented on src/pages/Profile/Profile.tsx
> +      }
Да, я здесь и проверяю, если значение null, тогда подставляю пустую строку

2021-03-03 18:23 UTC, iibadreeva reviewed
У меня сборка стала собираться с ошибкой, можно поправить
```
setState({
      avatar: user.avatar ?? '',
      id: user.id ?? 0,
      data: {
        first_name: user.first_name ?? '',
        second_name: user.second_name ?? '',
        display_name: user.display_name ?? '',
        email: user.email ?? '',
        login: user.login ?? '',
        phone: user.phone ?? ''
      }
    });
  }, [user]);
```
Кстати если мы не ожидаем ноль, можно просто использовать ||, а то знак ??  говорит что мне, что ноль имеет значение 
```
export type UserType = {
  id?: number;
  login: string;
  avatar: string | null;
  first_name: string;
  second_name?: string;
  display_name?: string | null;
  email?: string;
  phone?: string;
};
```

2021-03-03 18:23 UTC, iibadreeva commented on src/pages/Profile/Profile.tsx
> +  );
Можно объединить
```
const { user, isProfileView } = useSelector((state: AppState) => {
    return {
      user: userSelector(state),
      isProfileView: profileSelector(state)
    };
  });
```

2021-03-03 18:36 UTC, AndZhr commented on src/pages/Profile/Profile.tsx
> +  );
Всё поправил

2021-03-03 19:20 UTC, iibadreeva approved these changes

2021-03-04 06:50 UTC, anastasia1188 approved these changes

2021-03-04 06:52 UTC, anastasia1188 commented on src/pages/Profile/Profile.tsx
> +  );
rebase вроде стоит сделать, чтобы мои правки подтянулись

2021-03-04 08:37 UTC, merged