API лидербоард
capetown-team/capetown-game pull request #82
Opened 2021-03-14 09:41 UTC by anastasia1188

2021-03-14 14:34 UTC, iibadreeva requested changes
Я сыграла в игру, завершила, но на доске так и не появилась
Почему-то у нас не используется redux?
При обновлении страницы F5 все пропадает

2021-03-14 14:34 UTC, iibadreeva commented on src/pages/Leaders/data.tsx
> +};
data.tsx был временный вариант пока не будет настроен redux
И почему не используется redux?

2021-03-14 14:34 UTC, iibadreeva commented on src/pages/Leaders/Leaders.tsx
> +    }
Я не поняла эту конструкцию, работает и без этих правок

2021-03-14 14:34 UTC, iibadreeva commented on src/middlewares/api.tsx
> +export type ResponseLeaderBoardType = {
Описано, но ни где не используется

2021-03-15 08:34 UTC, anastasia1188 commented on src/pages/Leaders/data.tsx
> +};
думаю redux хранилище в данном случае не обязательно, тут всего лишь одна ручка post отправляет данные, другая на странице лидербоард подтягивает данные, нет такой необходимости как для пользователя создавать под это отдельное хранилище

2021-03-15 08:34 UTC, anastasia1188 commented on src/pages/Leaders/Leaders.tsx
> +    }
поправила

2021-03-15 08:34 UTC, anastasia1188 commented on src/middlewares/api.tsx
> +export type ResponseLeaderBoardType = {
поправила

2021-03-15 10:43 UTC, AndZhr approved these changes

2021-03-15 11:00 UTC, DmitryKhitrin commented on src/middlewares/api.tsx
> +  const postLiderBoardResult = async (data: LeaderBoardType) => {
Зачем зашивать в название, что это именно post? Лучше заменить на `setLiderBoardResult`

2021-03-15 11:01 UTC, DmitryKhitrin commented on src/middlewares/api.tsx
> +export const postLiderBoardAll = async (data: LeaderBoardAllType) => {
set

2021-03-15 11:01 UTC, DmitryKhitrin commented on src/pages/Game/script/Engine.tsx
> +    if (user !== undefined) this.user = user;
Пропущены `{}`.

2021-03-15 11:02 UTC, DmitryKhitrin commented on src/pages/Leaders/Leaders.tsx
> +      for (let i = 0; i < response.data.length; i += 1) {
Это стоит сделать через метода массива `map`

2021-03-15 11:04 UTC, DmitryKhitrin commented on src/pages/Leaders/Leaders.tsx
> +      for (let i = 0; i < response.data.length; i += 1) {
```
const result = response.data.map((data: {pacmanPlayer, pacmanAvatar, pacmanScore}) => ({
    i: i + 1,
    pacmanPlayer,
    pacmanAvatar,
    pacmanScore,
}))
```

2021-03-15 11:05 UTC, DmitryKhitrin commented on src/pages/Leaders/Leaders.tsx
> +      isMounted = false;
А зачем тут этот флажок? По идее useEffect отрабатывает только если компонент смаунчен

2021-03-15 11:10 UTC, iibadreeva reviewed
Все же мне кажется можно использовать redux как на запись и на чтение

2021-03-15 11:24 UTC, iibadreeva requested changes
Я все же считаю что необходимо использовать redux, как на чтение. так и на запись, 
Так же запросы описаны в middlewares и только одно название говорит о связке со store
Если писать все запросы и хранить на странице с шаблонами, зачем тогда мы вообще подгружали и использовали redux?
Плюс я не вижу обработки  лоудера, ошибок, а так выглядит грязным кодом, если все вперемешку делать 
Ты поставила лимит 10, хотя у нас есть пагинация, в пагинации используется до 7 элементов, то есть всегда не более 2-х вкладок?

2021-03-15 13:19 UTC, anastasia1188 commented
> Я все же считаю что необходимо использовать redux, как на чтение. так и на запись,
> Так же запросы описаны в middlewares и только одно название говорит о связке со store
> Если писать все запросы и хранить на странице с шаблонами, зачем тогда мы вообще подгружали и использовали redux?
> Плюс я не вижу обработки лоудера, ошибок, а так выглядит грязным кодом, если все вперемешку делать
> Ты поставила лимит 10, хотя у нас есть пагинация, в пагинации используется до 7 элементов, то есть всегда не более 2-х вкладок?
ок, подключаю через редакс, лимит убираю, был в тестовом запросе

2021-03-17 19:51 UTC, iibadreeva approved these changes
Возможно ты не догрузила изменения поскольку нет файлов server webpack и config написан на js, для запуска проекта пришлось скачивать webpack-dev-server

2021-03-18 07:22 UTC, merged