Sprint 8 task routing services
capetown-team/capetown-game pull request #98
Opened 2021-04-09 09:34 UTC by anastasia1188

2021-04-10 01:55 UTC, iibadreeva requested changes
1. api, db не используется prettier или eslint
2. Зачем надо было разделять в reducers/forum на несколько папок? 
### Не большие вопросы по ручкам, 
1 почему ручки написаны на том же порте что и сервер (я думала  будет другой)? 
2 Создана пака api/services/ - Зачем надо было писать запросы тут?
3 api/forum/topic/14
возвращает 
`{
id: 14,
name: "Articles ",
content: "Articles ",
userId: 7
}`
-- Предполагается возвращать тему с комментариями, просто где эта ручка может быть использована?
4 /api/forum/topic
передаю 
`{
    "name":"new name",
    "content":"password123",
    "userid":1096
}`
получаю
`{
    "error": {
        "type": "db error",
        "data": "{\"name\":\"SequelizeValidationError\",\"errors\":[{\"message\":\"topic.userid cannot be null\",\"type\":\"notNull Violation\",\"path\":\"userid\",\"value\":null,\"origin\":\"CORE\",\"instance\":{\"id\":null,\"name\":\"new name\",\"content\":\"password123\"},\"validatorKey\":\"is_null\",\"validatorName\":null,\"validatorArgs\":[]}]}"
    }
}`
![Без названия (1)](https://user-images.githubusercontent.com/13451776/114254546-b4209b00-99b8-11eb-9761-9ec7b86dcab5.png)

5 /comments, ты планируешь хранить все комментарии в одном месте? Есть ли в этом смысл? Может было был бы смысл хранить комментарии в текущем топике? migrations.sql я добавила комменты из твоих заготовок
![Без названия (2)](https://user-images.githubusercontent.com/13451776/114254569-dd412b80-99b8-11eb-9ec7-5a6d3858e5e2.png)
но происходит ошибка при обращении [https://local.ya-praktikum.tech:5000/api/forum/comments](url) 
`{
error: [
"db error",
{ }
]
}`
6 replies тоже ошибка

2021-04-10 01:55 UTC, iibadreeva commented on server/middlewares/server-user-auth-middleware.tsx
> +}
Ошибки на ts, ты не включаешь проверку? в созданных файлах 
server-user-auth-middleware.tsx
![Без названия](https://user-images.githubusercontent.com/13451776/114254421-f4cbe480-99b7-11eb-8400-8cdad4305a44.png)

2021-04-10 09:34 UTC, DmitryKhitrin commented on db/models/comment.tsx
> +  };
EOF

2021-04-10 09:34 UTC, DmitryKhitrin commented on db/models/topic.tsx
> +  };
EOF

2021-04-14 20:43 UTC, iibadreeva approved these changes

2021-04-14 20:43 UTC, iibadreeva commented on server/api/services/forumService.ts
> +  );
У меня тут ошибки ts, надо будет поправить 
![2021-04-14 (2)](https://user-images.githubusercontent.com/13451776/114776362-12fc6080-9d7b-11eb-855f-57ebe3d7acdb.png)

2021-04-15 06:06 UTC, merged